# Generated by Django 5.1.2 on 2024-10-30 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routes')),
            ],
        ),
    ]
