# Generated by Django 5.1.2 on 2024-11-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='route_id',
            new_name='route',
        ),
    ]
