# Generated by Django 5.1.2 on 2024-11-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_client_id_tickets_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='client',
            new_name='customer',
        ),
    ]
