# Generated by Django 5.1.2 on 2024-11-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0001_initial'),
        ('drivers', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busses',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='busses',
            name='route_id',
        ),
        migrations.AddField(
            model_name='busses',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='drivers.drivers'),
        ),
        migrations.AddField(
            model_name='busses',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='routes.routes'),
        ),
    ]
