# Generated by Django 5.1.2 on 2024-10-30 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('travel_time', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('number_of_available_seats', models.IntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busses.busses')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routes')),
            ],
        ),
    ]
