# Generated by Django 5.1.2 on 2024-11-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_route_id_stop_route_remove_routes_bus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='travel_time',
        ),
    ]
