# Generated by Django 5.1.2 on 2024-11-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_routes_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.routes'),
        ),
    ]
